{
 "title": "Flask App Observability Dashboard",
 "tags": [
  "flask",
  "observability",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Запросы к главной странице",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/\", status=\"200\"}",
     "legendFormat": "Запросы к главной странице (status 200)"
    }
   ]
  },
  {
   "title": "Гистограмма времени отклика (Heatmap)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket{method=\"GET\", path=\"/\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Логи приложения Flask",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"}"
    }
   ]
  }
 ]
}